.github/workflows/lint.yml
.golangci.yml
Makefile
README.md
go.mod
tools/Dockerfile

Since we currently don't plan on using cometbft-db v0.8.0 in CometBFT v0.34.x, it seems safe to bump the minimum supported Go version for the cometbft-db v0.8.x series to Go v1.20.
Also, with regard to https://github.com/cometbft/cometbft/pull/777#issuecomment-1593743103, doing so will allow us to build a `cometbft-db-testing` image based on Go v1.20 that we can use as a base for our [CometBFT E2E test image](https://github.com/cometbft/cometbft/blob/6f7746225c378b4f4e40e80a669226385cda8bfb/test/e2e/docker/Dockerfile) that pre-packages manually built cleveldb and RocksDB support.
This way our E2E test image will be able to use whatever the current supported underlying versions of cleveldb and RocksDB have been tested with cometbft-db.
I've also updated the linting settings to use the …

Bump minimum Go version to v1.20

---

.changelog/unreleased/go-version/98-bump-go-v1.21.md
README.md
go.mod
go.sum
tools/Dockerfile

In order to update the CometBFT E2E tests on `main` and for `v1.x` to make use of the latest release of cometbft-db (as per https://github.com/cometbft/cometbft/pull/777#issuecomment-1593743103), we'll need to build the Docker test image using Go v1.21.
This PR needs to be applied before #97.

Update to Go v1.21

---

.changelog/config.toml
.changelog/v0.9.0/dependencies/97-update-rocksdb.md
.changelog/v0.9.1/summary.md
CHANGELOG.md

This will help trigger the cutting of the cometbft-db-testing image with support for both `linux/amd64` and `linux/arm64` platforms.
Also updates the changelog sorting/ordering to match CometBFT's.
[CHANGELOG rendered](https://github.com/cometbft/cometbft-db/blob/release/v0.9.1/CHANGELOG.md)

Release v0.9.1

---

.github/workflows/govulncheck.yml

Noticed a few dependency update workflows are failing and it seems to be due to GitHub Actions caching a slightly outdated version of Go.
We do this in CometBFT to ensure we always have the absolute latest version of Go: https://github.com/cometbft/cometbft/blob/148eebdab2fbf44cec4f1de3c07ce53ef02d4509/.github/workflows/govulncheck.yml#L22

ci: Always check for latest Go version in govulncheck workflow

---

Makefile

This PR 
* adds pebble to CI test runs for cometbft-db

fix: add pebble to the ci test runs

---

pebble.go

As described in the comment, there is no specific need to initialize the DB for the batch version of pebble DB. But if we want to add functions like compaction, we need this to be initialized to something to avoid null pointer exceptions.

fix(pebbledb): Initialize DB in batchDB constructor

---

.github/workflows/lint.yml
go.mod
go.sum

For some reason codeql demands the exact version of go in go.mod

fix: codeql

---

.changelog/unreleased/features/153-deprecate-boltdb-cleveldb.md
README.md
boltdb.go
cleveldb.go

Deprecate boltdb and cleveldb

---

.changelog/v0.13.0/features/168-iter-key.md
.changelog/v0.13.0/summary.md
backend_test.go
badger_db.go
common_test.go
goleveldb_iterator.go
pebble.go
rocksdb_iterator.go
types.go

Closes #156.
The:
- `Iterator.Key()` API implementations of levelDB, badgerDB, and pebbleDB no longer return a copy of the key.
- `Iterator.Value()` API implementations of levelDB and pebbleDB no longer return a copy of the value.
Rather, as the updated docs reflect, the caller is responsible for creating a copy of the slice if they want to modify it.
See my further comments about [rocksdb](https://github.com/cometbft/cometbft-db/pull/168#issuecomment-2222932698) and [badgerdb](https://github.com/cometbft/cometbft-db/pull/168#issuecomment-2223080924) below.

feat!: Iterator `Key()` and `Value()` no longer return a copy

---

.changelog/v0.13.0/breaking-changes/155-remove-bolt-cleveldb.md
.changelog/v0.13.0/summary.md
CHANGELOG.md

Closes #175.
The changelog of release v0.13.0 does not mention that we removed support for boltDB and clevelDB in this release.
This PR adds this information to the changelog.

Update v0.13.0 Changelog

---

.changelog/unreleased/dependencies/177-reinstate-boltdb-cleveldb.md
Makefile
README.md
boltdb.go
boltdb_batch.go
boltdb_iterator.go
boltdb_test.go
cleveldb.go
cleveldb_batch.go
cleveldb_iterator.go
cleveldb_test.go
db.go
go.mod
go.sum
util_test.go

We have decided to reinstate BoltDB and CLevelDB. These will remain marked as deprecated until a future version of CometBFT, where we plan to discontinue cometBFT-db and standardize on a single backend database.
This PR:
- reverts #155 to reinstate BoltDB and clevelDB as available DBs. However, we mark them as deprecated to warn users that we'll drop them in a future release.
- updates BoltDB and ClevelDB's `Iterator` APIs to comply with #168

Reinstate BoltDB and ClevelDB as backend DBs

---

go.mod

We accidentally created the tag `v0.9.2` at a wrong point in the commit history.
Therefore, we have to retract this version to prevent its use.
This PR retracts `v0.9.2` from the `go.mod` of the project.

Retract `v0.9.2`

---

.changelog/unreleased/breaking-changes/4039-go-2024-3107.md
.github/workflows/go-version.env
go.mod
tools/Dockerfile

Refs https://github.com/cometbft/cometbft/issues/4039

build(deps): Bump minimum Go version to v1.23

---

.changelog/unreleased/dependencies/197-bump-go.md
.github/workflows/go-version.env
.golangci.yml
go.mod
tools/Dockerfile

chore: Update go version to `1.22.7` on `v0.14.x` release branch

---

.changelog/unreleased/breaking/578-add-goleveldb-build-flag.md
.golangci.yml
backend_test.go
common_test.go
db.go
goleveldb.go
goleveldb_batch.go
goleveldb_iterator.go
goleveldb_test.go
memdb.go
memdb_batch.go
pebble.go
pebble_test.go
prefixdb.go
test_helpers.go
types.go
util.go

Because goleveldb won't be the default CometBFT DB in the future.
Also, minor updates to CI/linting and improvements to logic in pebbledb.

feat!: add `goleveldb` and remove `pebbledb` build flag

---

.changelog/v0.15.0/dependencies/189-bump-gorocksdb-version.md
CHANGELOG.md

A changelog entry was missed about the RocksDB version bump

fix: add missing changelog entry for RocksDB bump

---

.github/workflows/docker.yml

so that we can publish `v1.0.2` image by manually triggering the job with `refName = v1.0.2`

ci: allow changing Git ref name in docker

---

.changelog/unreleased/bug-fixes/234-fix-arm64-build.md
.github/workflows/ci.yml
.github/workflows/docker.yml
tools/Dockerfile
tools/Dockerfile.arm64

Contributes to #234 
Removes `rocksdb` from docker due to segfault.
---

fix(tools): bring back arm64 target

---

.changelog/unreleased/dependencies/236-bump-go-version.md
.github/workflows/go-version.env
go.mod
tools/Dockerfile
tools/Dockerfile.arm64

includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command.

build(deps): bump Go version

---

.github/workflows/go-version.env
go.mod
tools/Dockerfile

This PR relaxes the Go restraint to 1.23. In modules that include it, it will require 1.23, but will be flexible to the patch version that module is on.
I removed the Github Action env variable since it doesn't look like we use it anymore. Perhaps in the recent Github Action refactors we removed it's usage. (If workflows start failing I will need to restore this, but I can't find any references to it in the code).
---

chore: relax Go version constraint to 1.23

---

.github/workflows/docker.yml

```
The workflow is not valid. Unrecognized named-value: 'matrix'. Located
at position 1 within expression: matrix.platform
.github/workflows/docker.yml (Line: 78, Col: 14): Unexpected symbol:
'digest-linux/amd64'. Located at position 34 within expression:
needs.build-image-at-tag.outputs.digest-linux/amd64
```

ci: docker: fix unrecognized named-value

---

.changelog/unreleased/dependencies/260-bump-go.md
.github/workflows/go-version.env
go.mod
tools/Dockerfile

build(deps): bump Go version to 1.22.12
